name: CI

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.7'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true

  test:
    name: unittest
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.7'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9' 
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f lesson2/requirements.txt ]; then pip install -r lesson2/requirements.txt; fi

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: pytest --cov-config=.coveragerc --cov=. lesson2 --cov-report xml --cov-report term-missing:skip-covered
          coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
